# Generated by Django 3.2.11 on 2022-01-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0006_auto_20220127_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
