# Generated by Django 3.2.11 on 2022-01-28 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolistapp', '0007_auto_20220127_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
