# Generated by Django 3.2.11 on 2022-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0008_auto_20220129_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
