# Generated by Django 3.2.11 on 2022-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0010_auto_20220130_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
